---
all:
  children:
    stage:
      children:
        production:
          hosts:
            vcsa:
        development:
          hosts:
    location:
      children:
        phoenix:
        denver:
        lab:
          hosts:
            vcsa:
    devicetype:
      children:
        firewall:
        vcenter:
          hosts:
            vcsa:
        switch:
        wlanap:
    servers:
      children:
        windows:
        linux:
    vendor:
      children:
        vmware:
          hosts:
            vcsa:
        redhat:
