---
all:
  children:
    stage:
      children:
        production:
          hosts:
            core01:
            core02:
        development:
          hosts:
            labrouter:
    location:
      children:
        phoenix:
        denver:
        lab:
          hosts:
            labrouter:
    networktype:
      children:
        campuslan:
        cloud:
        corenetwork:
        datacenter:
        internetedge:
        extranetedge:
        remotebranch:
        wan:
        labnetwork:
          hosts:
            labrouter:
    devicetype:
      children:
        firewall:
        loadbalancer:
        router:
          hosts:
            labrouter:
        switch:
        wlanap:
    servers:
      children:
        windows:
        linux:
    vendor:
      children:
        cisco-ios:
          hosts:
            labrouter:
        cisco-nxos:
        arista:
        juniper:
