---
all:
  hosts:
    localhost:
      ansible_python_interpreter: /Users/davidking/Documents/developer/IaC_VM/.venv/bin/python
  children:
    stage:
      children:
        production:
          hosts:
            vcsa:
        development:
          hosts:
    location:
      children:
        phoenix:
        denver:
        lab:
          hosts:
            vcsa:
    devicetype:
      children:
        firewall:
        vcenter:
          hosts:
            vcsa:
        switch:
        wlanap:
        azure:
          hosts:
            azure_vnet01:
    servers:
      children:
        windows:
        linux:
          hosts:
            linux01:
    vendor:
      children:
        vmware:
          hosts:
            vcsa:
        redhat:
        azure:
          hosts:
            azure_vnet01:
