---

- name: Gather VM Facts
  community.vmware.vmware_about_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
  delegate_to: localhost
  register: vcenter_facts

- name: Display vCenter Facts
  ansible.builtin.debug:
    var: vcenter_facts
